### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by oubowu** [XBeats/and_swipeback#1]
这个思路的话，每个Activity都要添加上一个的ContentView,性能方面会不会有影响？

**Comment by oubowu** [comment]
明白了，原来是取出View再画到一个自定义的View上面，其实我觉得也可以把画渐变阴影都放在那个View上面做，还有我建议把decorview传去绘制比较好，比如我Activity都是用style定义了默认backgroud颜色为灰色，所以contentview是不设背景色的，所以滑动回来的时候那个contentview背景色是黑色的

**Comment by XBeats** [comment]
其实是将上一个Activity的ContentView的子View添加到当前Activity中，在滑动或动画展示过程是都是contentView的直接位置变换；只有在滑动返回启动时，即当前Activity finish之前，去将上个Activity的contentView缓存显示到自定义的View中，这样做的目的是为了防止，在Activity关闭回到上个Activity时发生闪屏现象。至于你说的背景黑色的问题只要将上个Activity的contentView设置背景色为getWindowBackgroundColor() （该方法已经提供了），不过正常情况下app的背景色都是gray，所以并不需要去设置了。
