### ISSUE TITLE
按下返回键，屏幕回到上一个界面时，有黑边

### ISSUE THREAD

**Issue by qiu1992** [XBeats/and_swipeback#10]
如题，源码跑出来的demo也有这个问题。如果是手指滑动屏幕，返回到上一个界面，就不会出现黑边。对了这个黑边在屏幕右侧，在快要回到上一个界面的时候，闪现

**Comment by XBeats** [comment]
不太明白你的意思呀，你确定是点击返回键返回上个界面有黑边吗，而不是滑动返回？

**Comment by qiu1992** [comment]
确定是点击【返回键】返回上个界面，在屏幕右侧有黑边，宽度是1-2毫米，一闪而过。滑动返回则不会。

**Comment by XBeats** [comment]
如果是点击返回键的话，那就和滑动返回机制无关了，可能是Activity的切换产生的动画。
