### ISSUE TITLE
没有效果

### ISSUE THREAD

**Issue by HeCaser** [XBeats/and_swipeback#12]
我的华为荣耀4x和p9Plus都没有效果,直接下载运行的,是不是还要配置下

**Comment by XBeats** [comment]
不会呀，直接运行时可以的，排除下是不是不支持public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {} 这个方法

**Comment by XBeats** [comment]
试用下gradle引用，compile 'com.aitangba:swipeback:1.0.0'
