### ISSUE TITLE
滑动的时候 是不是id会重复 

### ISSUE THREAD

**Issue by softrice** [XBeats/and_swipeback#16]
滑动的时候 页面叠加在一起 有可能这时候有些和id相关的动作被触发 会出现问题

**Comment by XBeats** [comment]
恩，不过可以通过View的findViewById方法来避免，setContentView的时候，根据自己的需求，在当前Activity的ContentView的找到需要的Id的view

**Comment by softrice** [comment]
这是个解决方法
但业务方有使用 `fragmentManager.beginTransaction().replace()`
现在采用的方法是背景上个 Activity 的 View
而直接使用PreviousPageView
也就是截图方案 感觉不会很影响性能
只是图是不会动而已
会不会有其它坑？

**Comment by XBeats** [comment]
截图方案在低端手机上的显示效果不是很好，有明显的卡顿效果，所以就放弃了 。根据自己的业务需求选择合理的方案吧
