### ISSUE TITLE
好用，奖励XBeats一朵小红花

### ISSUE THREAD

**Issue by protectedMan** [XBeats/and_swipeback#18]
![image](https://cloud.githubusercontent.com/assets/17565737/21208778/2520981c-c2ab-11e6-80ba-39135ab89aae.png)
不过能直接compile就更好了

**Comment by XBeats** [comment]
哈哈哈，近期准备支持compile了，期待吧~~

**Comment by XBeats** [comment]
compile 'com.aitangba:swipeback:1.0.0'，刚刚审核了。
