### ISSUE TITLE
Fragment 支持

### ISSUE THREAD

**Issue by 29995270** [XBeats/and_swipeback#2]
如果你打开 overDraw 的话，应该能看出来 微信 的UI部分使用了Fragment（比如会话界面），同样支持侧滑返回，并且背景界面也会在侧滑的时候跟随做视差滑动，如果使用 ActivityLifecycleCallback，则没法追踪 fragment 的界面。
不过微信的侧滑返回应该是混合了很多种方式，比如有些其他进程的界面的侧滑，应该就是普通的透明背景加 Swipebacklayout。
你的这种实现方式很有意思，感觉就算 activity 栈销毁重建也不会影响 侧滑返回，而且也没有 Swipebacklayout 的性能问题。
[https://github.com/29995270/WechatSwipeBack](url)
我也有做一个实现，但是没法处理 activity 栈被销毁的问题，也很难实际应用。

**Comment by XBeats** [comment]
在使用过程中，经常用fragment和PagerAdapter结合使用，本身是有滑动事件的，所以没有考虑Fragment；使用主题透明所带来的性能问题，可能你也知道，有点得不偿失；另外这套机制确实是不用去关心Activity 栈销毁重建，也没有很大的性能开销。

**Comment by XBeats** [comment]
刚刚看了你的WechatSwipeBack，将所有打开的Activity中的DragBackLayout用弱引用集合收集起来，然后依次展示滑动和动画，其实一开始我也这么想过，不过随着更多的深入，我发现，在某些手机的低内存情况下滑动机制不能很好的实现了，所以就放弃了；改用保存Activity的方式，利用ActivityThread自己去维护集合，会更好一些，至于Fragment滑动返回我觉得如果是返回上一个Activity问题不是很大，如果是返回上一个Fragment，就需要将SwipeWindowHelper构成参数改成View，这个我曾想过去扩展，不过后来我觉得自己的主题是Activity滑动返回，就限制成了Window。
