### ISSUE TITLE
为什么采用Handler的机制

### ISSUE THREAD

**Issue by softrice** [XBeats/and_swipeback#20]
基于该库做了一些修改,例如加入滑动触发的判断.目前的情况是左边的一些按钮无法触发.
改完后发现因为Handler和事件分发有时候会造成时序的混乱.直接把SwipeWindowHelper去除了继承Handler.
想问下当时是基于什么情况下考虑使用Handler.

**Comment by XBeats** [comment]
在处理View和手势之间的关系的时候，习惯性的用runnable和handler来处理了，滑动返回项目在最初阶段也是有其他的思路的，不过现在看来确定是可以不用handler的，这个点确实可以优化。

**Comment by XBeats** [comment]
你能详细描述一下遇到的 “因为Handler和事件分发有时候会造成时序的混乱” ，这种情况吗？

**Comment by softrice** [comment]
这个是在我优化了滑动触发后发生的。
原本的代码是直接把屏幕左边的事件拦截,有些左上角的按钮例如返回键就无法触发.
我做了点改动,仿造微信(ios)的风格,在手指在左侧滑动一定距离后才触发滑动返回.
但是后来测试发现,如果乱按,由于Handler发送的Message和点击滑动事件不一定会按照时间先后顺序执行.
由于滑动取消还涉及了动画,动画结束后又发送了Message,在我的代码里有几率出现问题.
原来的代码不会这样,只是我修改后这样.

**Comment by softrice** [comment]
因为改得比较苦恼,所以就去除了Handler.
