### ISSUE TITLE
右滑返回时，如果当前界面里面的view是可以上下滑动的话，那么每次往右边拖动都会使view往上拉

### ISSUE THREAD

**Issue by yinyiliang** [XBeats/and_swipeback#21]
在我需要右滑返回的界面，如果有webView、上下拉刷新、listview  所有这些可以上下拖动的视图，滑动关闭时都会让里面的视图往上滑动。

**Comment by XBeats** [comment]
你的意思是滑动动画结束后，返回到了上个Activity，这时这个Activity的View需要有刷新行为吗？我觉得这个可以放在Activity的生命周期中做呀。

**Comment by yinyiliang** [comment]
@XBeats  不是的  你QQ多少？我发个截图给你

**Comment by XBeats** [comment]
企业号2885194960，这个QQ不是个人的，最好给我发邮件吧，

**Comment by yinyiliang** [comment]
@XBeats 我发现出现我的问题的原因是，你在代码里判断是否满足滑动时，当由开始的不满足滑动，返回false，到满足条件的瞬间，你没有及时返回true，而是使用sendMessage移动了视图后才进行拦截，返回true，这个时候当前界面里的子view已经移动了。
![image](https://cloud.githubusercontent.com/assets/17920616/22007715/050ba066-dcb0-11e6-8e59-f05ac90db2d1.png) 当我加上那一句后，我这边就没问题了。

**Comment by XBeats** [comment]
恩，有点明白你的意思了，在满足滑动的瞬间，确定会返回false，但是对手势进行了偏移，这个触发是为了通知手势点下的View，这个瞬间将会触发Cancel手势，所以View的恢复操作都需要在接受到Cancel时进行恢复，看到你的这个下拉控件应该是自定义的所以你需要重新看下这个下拉控件有没有处理MotionEvent.ACTION_CANCEL的情况。

**Comment by XBeats** [comment]
查看下develop分支的最新代码就可以了
