### ISSUE TITLE
实现方式好奇葩，我提一句，微信的滑动返回使用的时api 19的hidden api,convertAcitivtyToTransluctent，你可以试试

### ISSUE THREAD

**Issue by hackware1993** [XBeats/and_swipeback#3]

**Comment by XBeats** [comment]
微信的实现方式，没有去考虑，只是参考了他的实现效果；这个思路也是由于目前接触到的需求来确定的，最低要求Api14及其以上，基本兼容各个手机；如果要用hidden api，当时可能需要用反射的方式，这样就需要去判断Api和不断地去维护，觉得有点得不偿失了。

**Comment by 29995270** [comment]
@hackware1993 能详细说明一下么，我试着对 activityA 在 start 新的activityB 后 调用 activityA 的 convertFromTranslucent ，确实没有了透明背景造成的性能问题，但是返回的时候 activityA 似乎被 stop 了，有一些动画效果无法被执行，我试了在返回之前 调用 activityA 的 convertToTranslucent，依旧没有效果。

**Comment by 29995270** [comment]
@hackware1993 我又尝试了一下 在 activityA 的生命周期里调用 上述方法，貌似一切正常了

@Override
    protected void onResume() {
        super.onResume();
        Utils.convertActivityToTranslucent(this);
    }

    @Override
    protected void onPause() {
        super.onPause();
        Utils.convertActivityFromTranslucent(BaseActivity.this);
    }

**Comment by 29995270** [comment]
@hackware1993 @XBeats 
很多启发，非常感谢，我换了思路把自己的实现重构了，现在基本不用担心性能和界面被销毁了

**Comment by hackware1993** [comment]
@29995270 convert方案是有兼容性问题的，不能做到通用，你要小心
