### ISSUE TITLE
ActionBar的问题。

### ISSUE THREAD

**Issue by Caij** [XBeats/and_swipeback#4]
如果存在ActionBar，ActionBar不会移动。

发现你这种实现方案挺新颖的，解决了设置Activity背景透明生命周期导致的性能问题。

**Comment by SSSSHIELD** [comment]
同上，性能6666

**Comment by XBeats** [comment]
由于现在大多项目使用Toobar，所以就没有再考虑ActionBar了。毕竟Toolbar的灵活性是显而易见的
