### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by SSSSHIELD** [XBeats/and_swipeback#5]
1：如果我在侧边栏中，点击View，进入新的Activity，此时滑动返回，下层的界面并不是侧边栏，而是Activity，可能这和你实现的方式有关，DecorView。。。
2：滑动冲突：侧边栏无法滑动展开了，，当然这个可以解决
3：还是因为使用了DecorView，导致首页的几个Tab点击时会时不时报null。。。
4：StatusBar问题，不能很好地兼容沉浸式，由于项目的需要，其中有两种沉浸式实现，但是侧滑库只能兼容其中一种，另一种没办法兼容，而且会导致低层Activity的状态栏高度X2。。

**Comment by XBeats** [comment]
你是意思是直接处理DecorView吗？现在的做法是处理id为content的ContentView的子view，也就是我们设置Activity.setContentView（View view）的这个View。

**Comment by SSSSHIELD** [comment]
就是这种处理方式，会导致上面的几个问题，但是不得不说这种方式很新颖，如果项目中没有侧边栏，没有完全透明statusbar的话，这个侧滑是很好的

**Comment by XBeats** [comment]
恩，确实，像你说的侧边栏和statusbar是没有考虑的，不过比较适用大部分情况了。这两种情况我再考虑下。
