### ISSUE TITLE
在魅族MX5上面滑动不了哦

### ISSUE THREAD

**Issue by Caibou** [XBeats/and_swipeback#6]
RT

**Comment by XBeats** [comment]
我怀疑可能是不支持public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {}这个方式，如果是的话，就需要手机将Activity存到自定义的集合中，在BaseActivity的生命周期中进行相应的处理

**Comment by XBeats** [comment]
现在已发现问题，可能是滑动监测区域太少了，现在已经做了调整，并提供gradle引用compile 'com.aitangba:swipeback:1.0.0'
