### ISSUE TITLE
提供gradle引用？

### ISSUE THREAD

**Issue by vihuela** [XBeats/and_swipeback#8]
期待后续完善

**Comment by XBeats** [comment]
还没有提供gradle引用，正在完善中~~

**Comment by ljf1172361058** [comment]
请问现在如何快速引用这个库呢？

**Comment by XBeats** [comment]
涉及的代码不多，所以没有提供gradle，现在只要拷贝到自己的项目中就好

**Comment by ljf1172361058** [comment]
@XBeats 作者你好,有没有具体的说明需要导入哪些文件呢?还是说要把这个库导进去才行呢？

**Comment by XBeats** [comment]
原理其实很简单的，关键文件SwipeWindowHelper.java和ActivityLifecycleHelper.java。还是需要看下逻辑的。

**Comment by XBeats** [comment]
现在已提供gradle引用compile 'com.aitangba:swipeback:1.0.0'。

**Comment by XBeats** [comment]
现在已提供gradle引用，compile 'com.aitangba:swipeback:1.0.0'。
