### ISSUE TITLE
如果上个页面控件存在Toolbar，屏幕旋转后导致Toolbar高度不变

### ISSUE THREAD

**Issue by oubowu** [XBeats/and_swipeback#9]
首先竖屏首页
![截图](http://p1.bqimg.com/567571/a50693dd45ef8ae4.png)
跳转至滑动页
![截图](http://p1.bqimg.com/567571/e02cb3ebe6c7bda1.png)
旋转屏幕至横屏
![截图](http://p1.bqimg.com/567571/7a8c52645af197df.png)
回到横屏时的首页
![截图](http://p1.bqimg.com/567571/3a4f4e3434438c0f.png)

你可以发现在横屏做侧滑时Toolbar的高度还是竖屏时的Toolbar高度；当你真正返回到首页发现横屏的Toolbar其实变小了；然后我如果一开始首页是横屏的话，跳转到侧滑页然后旋转至竖屏后Toolbar高度还是一开始横屏的高度；所以就是说人为添加到侧滑页的页面的Toolbar在屏幕旋转时Activity重建后出现异常

**Comment by XBeats** [comment]
恩，这个确实呢，毕竟上个Activity没有进行从新绘制View。

**Comment by oubowu** [comment]
用了下微信的，旋转没问题，不知道咋实现的；还有看下uc新的版本，侧滑的效果很炫酷
